server:
  servlet:
    context-path: /kafka

auth:
  type: OAUTH2
  oauth2:
    client:
      keycloak:
        clientId: kafka_kck_id
        clientSecret: kafka_kck_scr
        scope: openid
        issuer-uri: https://keycloak_url:7171/realms/project_name
        user-name-attribute: preferred_username
        client-name: keycloak
        provider: keycloak
        custom-params:
          type: oauth
